#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Mar 24 20:29:57 GMT+08:00 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
